### PR TITLE
Require base >= 4.11.

### PR DESCRIPTION
**Pull request by robx**
Ranged-sets-0.4.0 fails to build with base <= 10 / ghc 8.2 due to the missing Semigroup
class.

```
Data/Ranged/RangedSet.hs:74:31: error:
    Not in scope: type constructor or class ‘Semigroup’
   |
74 | instance DiscreteOrdered a => Semigroup (RSet a) where
   |                               ^^^^^^^^^
```

This is causing me build failures trying to build postgrest with older ghc versions.

Could you please also apply this change via hackage's "edit package information" to
ensure that cabal chooses Ranged-sets <0.4 when building with older ghc versions?

If you like, I'd be happy to test and submit a PR for a Ranged-sets-0.4.1 that builds
with older base versions.

### CODE REVIEW

**Comment by PaulJohnson** [comment]
OK, I've accepted the pull request and updated the metadata in Hackage. Let me know if that works and I'll close the report.

**Comment by robx** [comment]
Thanks! It seems though that you revised the test build-depends instead of the library build-depends: http://hackage.haskell.org/package/Ranged-sets-0.4.0/revisions/, would you mind also updating the library?

(Build failure here building postgrest with ghc 8.0 because it tries to use Ranged-sets-0.4.0: https://travis-ci.org/robx/postgrest/jobs/542330852)

**Comment by robx** [comment]
That was quick thank you! The build works now.
